apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "libretranslate.fullname" . }}
  labels:
    {{- include "libretranslate.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "libretranslate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "libretranslate.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "libretranslate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-chown
          image: busybox
          command: ['sh', '-c', 'chown -R 1032: /app/db /home/libretranslate/.local/cache /home/libretranslate/.local/db /home/libretranslate/.local/share']
          volumeMounts:
            - name: libretranslate-api-keys
              mountPath: /app/db
            - name: libretranslate-cache
              mountPath: /home/libretranslate/.local/cache
            - name: libretranslate-db
              mountPath: /home/libretranslate/.local/db
            - name: libretranslate-share
              mountPath: /home/libretranslate/.local/share
            - name: libretranslate-files-translate
              mountPath: /tmp/libretranslate-files-translate
      volumes:
        - name: libretranslate-api-keys
          {{- if .Values.persistence.apiKeys.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.apiKeys.existingClaim }}{{ .Values.persistence.apiKeys.existingClaim }}{{- else }}{{ template "libretranslate.fullname" . }}-api-keys{{- end }}
          {{- end }}
        - name: libretranslate-cache
          {{- if .Values.persistence.cache.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.cache.existingClaim }}{{ .Values.persistence.cache.existingClaim }}{{- else }}{{ template "libretranslate.fullname" . }}-cache{{- end }}
          {{- end }}
        - name: libretranslate-db
          {{- if .Values.persistence.db.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.db.existingClaim }}{{ .Values.persistence.db.existingClaim }}{{- else }}{{ template "libretranslate.fullname" . }}-db{{- end }}
          {{- end }}
        - name: libretranslate-share
          {{- if .Values.persistence.share.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.share.existingClaim }}{{ .Values.persistence.share.existingClaim }}{{- else }}{{ template "libretranslate.fullname" . }}-share{{- end }}
          {{- end }}
        - name: libretranslate-files-translate
          {{- if .Values.persistence.filesTranslate.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.filesTranslate.existingClaim }}{{ .Values.persistence.filesTranslate.existingClaim }}{{- else }}{{ template "libretranslate.fullname" . }}-files-translate{{- end }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: libretranslate-api-keys
              mountPath: /app/db
            - name: libretranslate-cache
              mountPath: /home/libretranslate/.local/cache
            - name: libretranslate-db
              mountPath: /home/libretranslate/.local/db
            - name: libretranslate-share
              mountPath: /home/libretranslate/.local/share
            - name: libretranslate-files-translate
              mountPath: /tmp/libretranslate-files-translate
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args: {{ .Values.args | toYaml | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
