apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "akaunting.fullname" . }}-nginx-config
data:
  default.conf: |
    # Generic startup file.
    user www-data;

    worker_processes auto;
    worker_cpu_affinity auto;

    error_log /var/log/nginx/error.log;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include mime.types;
        default_type application/octet-stream;
        access_log /var/log/nginx/access.log;
        sendfile on;
        keepalive_timeout 64;

        client_max_body_size 13m;
        index index.php index.html index.htm;

        # Upstream to abstract backend connection(s) for PHP.
        upstream php {
            server {{ include "akaunting.fullname" . }}:9000;
        }

        server {
            listen 80 default_server;
            server_name _;

            root /var/www/html;

            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Content-Type-Options "nosniff";

            index index.html index.htm index.php;

            charset utf-8;

            location / {
                try_files $uri $uri/ /index.php?$query_string;
            }

            # Prevent Direct Access To Protected Files
            location ~ \.(env|log) {
                deny all;
            }

            # Prevent Direct Access To Protected Folders
            location ~ ^/(^app$|bootstrap|config|database|overrides|resources|routes|storage|tests|artisan) {
                deny all;
            }

            # Prevent Direct Access To modules/vendor Folders Except Assets
            location ~ ^/(modules|vendor)\/(.*)\.((?!ico|gif|jpg|jpeg|png|js\b|css|less|sass|font|woff|woff2|eot|ttf|svg).)*$ {
                deny all;
            }

            error_page 404 /index.php;

            # Pass PHP Scripts To FastCGI Server
            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass php;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
            }

            location ~ /\.(?!well-known).* {
                deny all;
            }
        }
    }
