name: Publish Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'charts/**'
      - 'artifacthub-repo.yml'
      - 'README.md'

jobs:
  publish-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Package and Check Charts
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        git checkout main -- charts
        cd charts
        for d in */ ; do
          chart_name=$(basename "$d")
          chart_version=$(grep 'version:' "$d/Chart.yaml" | cut -d " " -f 2)
          if [ ! -f "../$chart_name-$chart_version.tgz" ]; then
            helm package "$d" -d ..
          else
            echo "Chart $chart_name-$chart_version already exists, skipping."
          fi
        done
        cd ..
        rm -r charts
        rm ./get_helm.sh

    - name: Copy Artifact Hub and README files
      run: |
        git checkout gh-pages
        git checkout main -- artifacthub-repo.yml README.md

    - name: Publish Charts to GitHub Pages
      run: |
        helm repo index --url https://f3k-tech.github.io/helm/ .
        git config user.name "FreekO"
        git config user.email "freek@olgers.com"
        git add .
        git commit -m "Publish Helm charts and additional files"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
